package work.kumarfamilynet.cinemarchive.data

import org.json.JSONArray
import org.json.JSONObject
import java.time.OffsetDateTime

/** A `shared_access_keys` row owned by the signed-in user — mirrors `SharedKey` in
 *  `apps/web/src/views/Profile.tsx`. [token] is generated by the database
 *  (`encode(gen_random_bytes(32), 'hex')`), never by the client. */
data class SharedAccessKey(
    val id: String,
    val token: String,
    val label: String?,
    val expiresAt: String?,
    val isActive: Boolean,
    val createdAt: String,
    val lastUsedAt: String?,
) {
    /** True when the key has an expiry that is at or before [nowMillis]. An expired key stays
     *  `is_active` (and keeps counting against the cap) until revoked — same as web. */
    fun isExpiredAt(nowMillis: Long): Boolean {
        val raw = expiresAt ?: return false
        val expiry = runCatching { OffsetDateTime.parse(raw).toInstant().toEpochMilli() }.getOrNull() ?: return false
        return expiry <= nowMillis
    }
}

/** The expiry choices in the web "Shared Access Links" form (`EXPIRY_OPTIONS`). */
enum class ShareExpiry(val label: String, val hours: Long?) {
    NEVER("Never expires", null),
    HOURS_24("24 hours", 24),
    DAYS_7("7 days", 24 * 7),
    DAYS_30("30 days", 24 * 30),
}

/** Which row of `share_scopes` an operation targets: a share link or an accepted friend.
 *  Mirrors web `ShareScopeTarget`. */
sealed interface ShareScopeTarget {
    data class Link(val sharedKeyId: String) : ShareScopeTarget
    data class Friend(val friendUserId: String) : ShareScopeTarget
}

/** Narrowing for a link/friend. A null list means "no restriction on that dimension"; the
 *  absence of any row means fully unrestricted (modelled as a null [ShareScope] from
 *  [SharingRepository.getShareScope]). Mirrors web `ShareScope`. */
data class ShareScope(
    val allowedGenres: List<String>?,
    val allowedStatuses: List<String>?,
) {
    val isUnrestricted: Boolean get() = allowedGenres == null && allowedStatuses == null
}

/** Read-only summary plus an immutable copy of the complete scoped graph. The graph is kept
 * only in the viewer's memory; it includes season cast and independent episode logs that the
 * owner Room schema does not yet represent. Callers get a fresh object, never shared mutable JSON.
 */
data class SharedLibraryTitle(
    val id: String,
    val tmdbId: Int,
    val mediaType: String,
    val title: String,
    val year: Int?,
    val posterUrl: String?,
    val status: String,
    val rating: Double?,
    val genres: List<String>,
    val addedAt: String?,
    val graphJson: String,
) {
    fun graph(): JSONObject = JSONObject(graphJson)
}

/** Result of opening a share link: the owner's user id (resolved from the key, independent of
 *  whether they own any visible titles) plus the scoped title list. */
data class SharedLibrary(
    val ownerUserId: String,
    val titles: List<SharedLibraryTitle>,
    val ledgerLayoutJson: String? = null,
)

/** The token does not identify a usable link: unknown, revoked, or expired. The server gives the
 *  three cases the same 42501 answer, so they cannot be told apart. */
class SharedLinkUnavailableException(message: String = "This share link is invalid, expired, or has been revoked.") :
    IllegalStateException(message)

/** Raised before any insert when the user already has [SharingRules.MAX_ACTIVE_LINKS] active links. */
class ShareLinkLimitException(message: String) : IllegalStateException(message)

object SharingRules {
    /** Web `MAX_ACTIVE_SHARED_KEYS`. Enforced client-side only — the database has no cap. */
    const val MAX_ACTIVE_LINKS = 10

    /** Public web origin (apps/web/public/CNAME; Vite `base` is `/`). */
    const val WEB_BASE_URL = "https://cinemarchive.kumarfamilynet.work/"

    /** Same shape as web `handleCopyLink`: `${origin}${pathname}?share=${token}`. */
    fun shareLink(token: String, baseUrl: String = WEB_BASE_URL): String = "$baseUrl?share=$token"

    fun activeCount(keys: List<SharedAccessKey>): Int = keys.count { it.isActive }

    fun atCap(keys: List<SharedAccessKey>): Boolean = activeCount(keys) >= MAX_ACTIVE_LINKS

    /** Accept pasted public links or bare tokens. Intent routing uses [tokenFromLink] only. */
    fun parseToken(input: String): String? {
        val trimmed = input.trim()
        return tokenFromLink(trimmed) ?: trimmed.takeIf(::validToken)
    }

    fun tokenFromLink(input: String): String? = runCatching {
        val uri = java.net.URI(input)
        val web = uri.scheme == "https" && uri.host == "cinemarchive.kumarfamilynet.work" &&
            uri.userInfo == null && (uri.port == -1 || uri.port == 443)
        val native = uri.scheme == "cinemarchive" && uri.host == "share"
        if (!web && !native) return@runCatching null
        val values = uri.rawQuery.orEmpty().split('&').mapNotNull { pair ->
            val parts = pair.split('=', limit = 2)
            if (parts.size == 2 && parts[0] == "share")
                java.net.URLDecoder.decode(parts[1], "UTF-8") else null
        }
        values.singleOrNull()?.takeIf(::validToken)
    }.getOrNull()

    private fun validToken(token: String): Boolean =
        token.isNotBlank() && token.length <= 512 && token.all { it.isLetterOrDigit() || it == '-' || it == '_' }

    /** ISO-8601 UTC expiry for [expiry] relative to [nowMillis]; null for [ShareExpiry.NEVER]. */
    fun expiresAtIso(expiry: ShareExpiry, nowMillis: Long): String? =
        expiry.hours?.let { java.time.Instant.ofEpochMilli(nowMillis + it * 60 * 60 * 1000).toString() }
}

internal fun parseSharedKeys(json: String): List<SharedAccessKey> {
    val array = JSONArray(json)
    return (0 until array.length()).map { parseSharedKey(array.getJSONObject(it)) }
}

internal fun parseSharedKey(row: JSONObject): SharedAccessKey = SharedAccessKey(
    id = row.getString("id"),
    token = row.getString("token"),
    label = row.optStringOrNull("label"),
    expiresAt = row.optStringOrNull("expires_at"),
    isActive = row.optBoolean("is_active", true),
    createdAt = row.optString("created_at"),
    lastUsedAt = row.optStringOrNull("last_used_at"),
)

internal fun parseShareScope(json: String): ShareScope? {
    val array = JSONArray(json)
    if (array.length() == 0) return null
    val row = array.getJSONObject(0)
    return ShareScope(row.optStringListOrNull("allowed_genres"), row.optStringListOrNull("allowed_statuses"))
}

internal fun parseSharedTitles(json: String, ownerUserId: String): List<SharedLibraryTitle> {
    val array = JSONArray(json)
    return (0 until array.length()).map { i ->
        val row = array.getJSONObject(i)
        validateSharedGraph(row, ownerUserId)
        SharedLibraryTitle(
            id = row.getString("id"),
            tmdbId = row.getInt("tmdb_id"),
            mediaType = row.getString("type"),
            title = row.getString("title"),
            year = if (row.isNull("year")) null else row.optInt("year"),
            posterUrl = row.optStringOrNull("poster_url"),
            status = row.getString("status"),
            rating = if (row.isNull("rating")) null else row.optDouble("rating"),
            genres = row.optStringListOrNull("genres").orEmpty(),
            addedAt = row.optStringOrNull("added_at"),
            graphJson = row.toString(),
        )
    }
}

/** Fail closed on a malformed cross-owner/parent response instead of exposing unrelated
 * nested rows. These checks supplement, rather than replace, the RPC's scope enforcement. */
private fun validateSharedGraph(title: JSONObject, owner: String) {
    check(title.getString("user_id") == owner) { "The shared title belongs to another owner." }
    val titleId = title.getString("id")
    fun children(parent: JSONObject, key: String, parentKey: String, parentId: String): List<JSONObject> {
        val rows = parent.optJSONArray(key) ?: return emptyList()
        return (0 until rows.length()).map { index -> rows.getJSONObject(index).also { row ->
            check(row.getString(parentKey) == parentId) { "The shared library contains an unrelated $key row." }
            check(row.optStringOrNull("user_id") == owner) { "The shared library contains an unverified owner's data." }
            check(!row.has("title_id") || row.getString("title_id") == titleId) { "The shared library contains another title's data." }
        } }
    }
    children(title, "title_cast", "title_id", titleId)
    children(title, "title_crew", "title_id", titleId)
    children(title, "viewings", "title_id", titleId)
    children(title, "seasons", "title_id", titleId).forEach { season ->
        children(season, "season_cast", "season_id", season.getString("id"))
    }
    children(title, "episodes", "title_id", titleId).forEach { episode ->
        listOf("episode_crew", "episode_watch_events", "episode_ratings", "episode_reviews").forEach { key ->
            children(episode, key, "episode_id", episode.getString("id"))
        }
    }
    // The RPC never returns these fields at any depth; reject accidental broadening before
    // retaining the response graph in memory.
    val privateKeys = setOf("cinema_outings", "ticket_image_path", "ticket_barcode_payload",
        "ticket_barcode_format", "booking_ref", "lists", "notifications", "access_token", "refresh_token")
    fun rejectPrivate(value: Any) {
        when (value) {
            is JSONObject -> value.keys().forEach { key ->
                check(key !in privateKeys) { "The shared library response contains private data." }
                rejectPrivate(value.get(key))
            }
            is JSONArray -> (0 until value.length()).forEach { rejectPrivate(value.get(it)) }
        }
    }
    rejectPrivate(title)
}

internal fun JSONObject.optStringListOrNull(key: String): List<String>? {
    if (!has(key) || isNull(key)) return null
    val array = optJSONArray(key) ?: return null
    return (0 until array.length()).map { array.getString(it) }
}
